- name: Placing elastic repo File
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Installing filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: present

#- name: Placing Expense Config File in Nginx
#  ansible.builtin.template:
#    src: filebeat.yml
#    dest: /etc/filebeat/filebeat.yml
#
#- name: Starting filebeat Service
#  ansible.builtin.systemd:
#    name: filebeat
#    state: restarted
#    enabled: yes