- name: Placing Expense Config File in Nginx
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Installing filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: present